export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_ITEM_REQUEST = "CATEGORY_ITEM_REQUEST";
export const CATEGORY_ITEM_SUCCESS = "CATEGORY_ITEM_SUCCESS";
export const CATEGORY_ITEM_FAIL = "CATEGORY_ITEM_FAIL";
