export const COURSE_DETAIL_TRYAIL_REQUEST = "COURSE_DETAIL_TRYAIL_REQUEST";
export const COURSE_DETAIL_TRYAIL_SUCCESS = "COURSE_DETAIL_TRYAIL_SUCCESS";
export const COURSE_DETAIL_TRYAIL_FAIL = "COURSE_DETAIL_TRYAIL_FAIL";
